import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electronAPI', {
  getLeads:            (f?: Record<string,unknown>) => ipcRenderer.invoke('leads:getAll', f),
  getLead:             (id: number)                 => ipcRenderer.invoke('leads:getById', id),
  saveLead:            (lead: unknown)              => ipcRenderer.invoke('leads:save', lead),
  deleteLead:          (id: number)                 => ipcRenderer.invoke('leads:delete', id),
  checkDuplicates:     (p: Record<string,unknown>)  => ipcRenderer.invoke('leads:checkDuplicates', p),
  getDashboardStats:   ()                           => ipcRenderer.invoke('leads:getDashboardStats'),
  getPriorityQueue:    ()                           => ipcRenderer.invoke('leads:getPriorityQueue'),
  searchCreators:      (f: Record<string,unknown>)  => ipcRenderer.invoke('discovery:searchCreators', f),
  getRisingCreators:   (f: Record<string,unknown>)  => ipcRenderer.invoke('discovery:getRisingCreators', f),
  getCampaigns:        ()                           => ipcRenderer.invoke('campaigns:getAll'),
  getCampaign:         (id: number)                 => ipcRenderer.invoke('campaigns:getById', id),
  saveCampaign:        (c: unknown)                 => ipcRenderer.invoke('campaigns:save', c),
  deleteCampaign:      (id: number)                 => ipcRenderer.invoke('campaigns:delete', id),
  getCampaignStats:    (id: number)                 => ipcRenderer.invoke('campaigns:getStats', id),
  getCampaignReports:  ()                           => ipcRenderer.invoke('reports:getCampaignReports'),
  getNicheReports:     ()                           => ipcRenderer.invoke('reports:getNicheReports'),
  getRecruiterReports: ()                           => ipcRenderer.invoke('reports:getRecruiterReports'),
  getAppSettings:      ()                           => ipcRenderer.invoke('settings:getAll'),
  saveAppSettings:     (s: unknown)                 => ipcRenderer.invoke('settings:saveAll', s),
  getRecruiters:       ()                           => ipcRenderer.invoke('settings:getRecruiters'),
  saveRecruiter:       (r: unknown)                 => ipcRenderer.invoke('settings:saveRecruiter', r),
  deleteRecruiter:     (id: number)                 => ipcRenderer.invoke('settings:deleteRecruiter', id),
  getNiches:           ()                           => ipcRenderer.invoke('settings:getNiches'),
  saveNiches:          (n: string[])                => ipcRenderer.invoke('settings:saveNiches', n),
  getScoringWeights:   ()                           => ipcRenderer.invoke('settings:getScoringWeights'),
  saveScoringWeights:  (w: unknown)                 => ipcRenderer.invoke('settings:saveScoringWeights', w),
  getDmTemplates:      ()                           => ipcRenderer.invoke('settings:getDmTemplates'),
  saveDmTemplate:      (t: unknown)                 => ipcRenderer.invoke('settings:saveDmTemplate', t),
  deleteDmTemplate:    (id: number)                 => ipcRenderer.invoke('settings:deleteDmTemplate', id),
  getExportColumns:    ()                           => ipcRenderer.invoke('settings:getExportColumns'),
  saveExportColumns:   (c: string[])                => ipcRenderer.invoke('settings:saveExportColumns', c),
  getStatusLabels:     ()                           => ipcRenderer.invoke('settings:getStatusLabels'),
  saveStatusLabels:    (l: string[])                => ipcRenderer.invoke('settings:saveStatusLabels', l),
  selectLogoFile:      ()                           => ipcRenderer.invoke('settings:selectLogoFile'),
  exportToExcel:       (p: unknown)                 => ipcRenderer.invoke('export:toExcel', p),
  selectExportPath:    ()                           => ipcRenderer.invoke('export:selectPath'),
  getReviewQueue:      (s: string, f: Record<string,unknown>) => ipcRenderer.invoke('quickReview:getQueue', s, f),
  processReviewAction: (id: number, a: string)      => ipcRenderer.invoke('quickReview:processAction', id, a),
  getPresets:          ()                           => ipcRenderer.invoke('presets:getAll'),
  savePreset:          (p: unknown)                 => ipcRenderer.invoke('presets:save', p),
  deletePreset:        (id: number)                 => ipcRenderer.invoke('presets:delete', id),
  togglePresetPin:     (id: number)                 => ipcRenderer.invoke('presets:togglePin', id),
});
